# Generated by Django 2.0.2 on 2018-03-26 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(choices=[('AD', 'Administrator'), ('TH', 'Teacher'), ('ST', 'Student'), ('AC', 'Anticheat')], default='TH', max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='lmsuser',
            name='role',
            field=models.ManyToManyField(blank=True, to='login.Role'),
        ),
    ]
