# Generated by Django 2.0.2 on 2018-03-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('course_level', models.FloatField()),
                ('teacher_feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('difficulty_index', models.FloatField()),
                ('duration_allowed', models.TimeField()),
                ('success_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('sheet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(max_length=25)),
                ('number_exercises', models.IntegerField()),
                ('end_date', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')),
            ],
        ),
        migrations.AddField(
            model_name='lmsuser',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lmsuser',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lmsuser',
            name='last_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lmsuser',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Sheet'),
        ),
    ]
