# Generated by Django 2.0.2 on 2018-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180407_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_question',
            name='question_status',
            field=models.CharField(choices=[('SK', 'Skipped'), ('CR', 'Correct'), ('IN', 'Incorrect'), ('ST', 'Started'), ('NL', 'Null')], default='NL', max_length=2, null=True),
        ),
    ]
