# Generated by Django 2.0.2 on 2018-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180326_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmsuser',
            name='password',
        ),
    ]
