# Generated by Django 2.0.2 on 2018-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180408_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course',
            name='overall_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
