# Generated by Django 2.0.2 on 2018-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student_course_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='overall_score',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
