# Generated by Django 2.0.2 on 2018-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student_course_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration_allowed',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='success_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='number_exercises',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='overall_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='student_course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='teacher_feedback',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='completed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='number_abort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='number_correct_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='number_of_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='number_of_tries',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='student_exercise_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='time_spend_by_exercises',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='time_spend_succeed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_exercise',
            name='total_time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_question',
            name='student_question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_question',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_sheet',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student_sheet',
            name='student_sheet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_sheet',
            name='total_time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
