# Generated by Django 2.0.2 on 2018-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180411_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
