# Generated by Django 2.0.2 on 2018-04-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180411_1614'),
        ('login', '0005_auto_20180410_1645'),
    ]

    operations = [
    ]
